# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_000',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_001',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_002',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_003',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_004',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_005',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_006',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_007',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_008',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_009',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_010',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_011',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_012',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_013',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_014',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_015',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_016',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_017',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_018',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_019',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_020',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_021',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_022',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_023',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_024',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_025',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_026',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_027',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_028',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_029',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_030',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_031',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_032',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_033',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_034',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_035',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_036',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_037',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_038',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_039',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_040',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_041',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_042',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_043',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_044',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_045',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_046',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_047',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_048',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_049',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_050',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_051',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_052',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_053',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_054',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_055',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_056',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_057',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_058',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_059',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_060',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_061',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_062',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_063',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_064',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_065',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_066',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_067',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_068',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_069',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_070',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_071',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_072',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_073',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_074',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_075',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_076',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_077',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_078',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_079',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_080',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_081',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_082',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_083',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_084',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_085',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_086',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_087',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_088',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_089',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_090',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_091',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_092',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_093',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_094',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_095',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_096',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_097',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_098',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_099',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_100',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src_word', models.CharField(max_length=50)),
                ('tar_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='catalog_ids',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('catalog', models.CharField(max_length=50)),
            ],
        ),
    ]
